# Generated by Django 4.0.4 on 2022-06-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='products',
            new_name='product',
        ),
    ]
