# Generated by Django 4.0.4 on 2022-06-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_cart_product_order_cartproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
