# Generated by Django 4.0.4 on 2022-06-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_rename_quantify_cartproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Customer',
            new_name='customer',
        ),
    ]
